python/Web/hr_ptcc_project/employee_profile/urls.py
from django.urls import path
from . import views, apiViews

app_name = 'employee_profile'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.EmployeeDetailView.as_view(), name='employee_details'),
    path('save_changes', apiViews.save_changes, name='save_changes'),
    path('generate_leave_registry', apiViews.generate_leave_registry, name='generate_leave_registry'),
    path('download_file', apiViews.download_file, name='download_file'),
    path('add_employee', apiViews.add_employee, name='add_employee'),
    path('delete_employee', apiViews.delete_employee, name='delete_employee')
]

python/Web/hr_ptcc_project/hr_ptcc_project/urls.py
from django.contrib import admin
from django.urls import path, include
from employee_profile.views import upload_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employee_profile/', include('employee_profile.urls')),
    path('upload_files', upload_view, name='upload_view'),
    path('', include("django.contrib.auth.urls"))
]

python/Web/hr_ptcc_project/employee_profile/models.py
from django.db import models
from django.core import serializers
import datetime


class Employee(models.Model):
    REGULAR = 'R'
    REGULAR1 = 'R1'
    PROBATION = 'P'

    employee_status_choices = [
        (REGULAR, 'Regular Employee'),
        (REGULAR1, 'Regular1 Employee'),
        (PROBATION, 'Probationary Employee')
    ]

    employee_tin_id = models.IntegerField(default=0, unique=True)
    name = models.CharField(max_length=200)
    probation_date = models.DateField()
    hired_date = models.DateField()
    sl_start_date = models.DateField()
    regularization_date = models.DateField()
    employee_status = models.CharField(max_length=2,
                                       choices=employee_status_choices,
                                       default=PROBATION)
    prev_vl_bal = models.FloatField(default=0.0)
    prev_sl_bal = models.FloatField(default=0.0)

    def __str__(self):
        return self.name

    def get_total_leaves_taken(self):
        leaves_taken_obj_list = self.leave_set.all()
        sum_vl_taken = 0
        sum_sl_taken = 0

        for leaves_taken_obj in leaves_taken_obj_list:
            if leaves_taken_obj.type == "VL":
                sum_vl_taken += leaves_taken_obj.days
            elif leaves_taken_obj.type == "SL":
                sum_sl_taken += leaves_taken_obj.days

        return round(sum_vl_taken, 3), round(sum_sl_taken, 3)

    def get_earned_leaves(self):
        vl_list, sl_list = self.get_vl_sl_list()
        return zip(vl_list, sl_list)

    def get_leaves_taken(self):
        return serializers.serialize("json", self.leave_set.all())

    def get_offenses(self):
        return serializers.serialize("json", self.offense_set.all())

    def get_earned_vl_list(self):
        vl_list, sl_list = self.get_vl_sl_list()
        vl_list_serialized = serializers.serialize("json", vl_list)
        return vl_list_serialized

    def get_earned_sl_list(self):
        vl_list, sl_list = self.get_vl_sl_list()
        sl_list_serialized = serializers.serialize("json", sl_list)
        return sl_list_serialized

    def get_total_leaves(self):
        vl_list, sl_list = self.get_vl_sl_list()
        total_vl = self.prev_vl_bal
        total_sl = self.prev_sl_bal
        for vl in vl_list:
            total_vl += vl.value

        for sl in sl_list:
            total_sl += sl.value

        total_vl = round(total_vl, 3)
        total_sl = round(total_sl, 3)

        return total_vl, total_sl

    def get_vl_sl_list(self):
        emp_leaves = self.earnedleave_set.all()
        vl_list = []
        sl_list = []

        for leave in emp_leaves:
            if leave.type == 'VL':
                vl_list.append(leave)
            elif leave.type == 'SL':
                sl_list.append(leave)
        vl_list.sort(key=lambda x: x.cut_off)
        sl_list.sort(key=lambda x: x.cut_off)
        return vl_list, sl_list

    def get_timesheet_summary(self):
        emp_timesheet = self.timesheet_set.all()

        emp_timesheet_list = []
        for timesheet in emp_timesheet:
            if timesheet.time_in > datetime.time(hour=9, minute=0, second=0):
                late = 'YES'
            else:
                late = 'NO'

            if (timesheet.time_out - timesheet.time_in) < 8:
                ut = 'YES'
            else:
                ut = 'NO'

            emp_timesheet_list.append({'date': timesheet.date,
                                       'time_in': timesheet.time_in,
                                       'time_out': timesheet.time_out,
                                       'late': late,
                                       'ut': ut})
        return emp_timesheet_list


class Leave(models.Model):
    VL = 'VL'
    SL = 'SL'

    type_choices = [
        (VL, 'Vacation Leave'),
        (SL, 'Sick Leave')
    ]

    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    date = models.DateField()
    days = models.FloatField(default=0.0)
    type = models.CharField(max_length=2,
                            choices=type_choices,
                            default=VL)


class Offense(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    date = models.DateField()
    offense_name = models.CharField(max_length=20)


class Earnedleave(models.Model):
    VL = 'VL'
    SL = 'SL'

    type_choices = [
        (VL, 'Vacation Leave'),
        (SL, 'Sick Leave')
    ]

    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    cut_off = models.DateField()
    value = models.FloatField(default=0.0)
    type = models.CharField(max_length=2,
                            choices=type_choices,
                            default=VL)


class Timesheet(models.Model):

    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    date = models.DateField()
    time_in = models.TimeField()
    time_out = models.TimeField()
    project = models.CharField(max_length=200)

python/Web/hr_ptcc_project/employee_profile/forms.py
from django import forms


class EmployeeForm(forms.Form):
    sl_start_date = forms.DateField()
    regularization_date = forms.DateField()
    employee_status = forms.CharField(max_length=2)

python/Web/hr_ptcc_project/employee_profile/views.py
import csv
import io
from django.views import generic
from .models import Employee, Leave, Earnedleave, Offense, Timesheet
from django.contrib.auth.decorators import permission_required
from django.http import JsonResponse
from django.shortcuts import  redirect
import logging
import dateutil.parser
import datetime
import calendar
logger = logging.getLogger(__name__)


class IndexView(generic.ListView):
    template_name = 'employee_profile/index.html'
    context_object_name = 'latest_employee_list'

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return redirect('index')
        query = self.request.GET.get('search')
        if query:
            object_list = Employee.objects.filter(name__icontains=query)
        else:
            object_list = Employee.objects.order_by('name')
        return object_list

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('login')
        else:
            return super(IndexView, self).dispatch(request, *args, **kwargs)


class EmployeeDetailView(generic.DetailView):
    model = Employee
    template_name = 'employee_profile/employee_details.html'


@permission_required('admin.can_add_log_entry')
def upload_view(request):
    csv_file = request.FILES['file']
    csv_file_name = csv_file.name
    log_error = []
    message_header = 'Upload Done'

    if not csv_file_name.endswith('.csv'):
        return JsonResponse({"head": "Error", "body": "File must be CSV"})

    data_set = csv_file.read().decode('UTF-8')
    io_string = io.StringIO(data_set)
    next(io_string)

    if csv_file_name == "employee.csv":
        for column in csv.reader(io_string, delimiter=',', quotechar="|"):
            try:
                probation_date = (dateutil.parser.parse(column[2])).strftime("%Y-%m-%d")
                hired_date = (dateutil.parser.parse(column[3])).strftime("%Y-%m-%d")
                sl_start_date = (dateutil.parser.parse(column[4])).strftime("%Y-%m-%d")
                regularization_date = (dateutil.parser.parse(column[5])).strftime("%Y-%m-%d")

                _, created = Employee.objects.update_or_create(
                    employee_tin_id=column[0],
                    name=column[1],
                    probation_date=probation_date,
                    hired_date=hired_date,
                    sl_start_date=sl_start_date,
                    regularization_date=regularization_date,
                    employee_status=column[6],
                    prev_vl_bal=column[7],
                    prev_sl_bal=column[8],
                )
            except Exception as e:
                log_error.append(str(e))

        if log_error:
            message_body = f"[WARNING] There are errors found in your csv file: {log_error}"
        else:
            message_body = "All data has uploaded successfully"

    elif csv_file_name == "leaves.csv":
        for column in csv.reader(io_string, delimiter=',', quotechar="|"):
            try:
                employee_tin_id = int(column[0])
                employee = Employee.objects.get(employee_tin_id=employee_tin_id)
                date_obj = (dateutil.parser.parse(column[2])).strftime("%Y-%m-%d")
                days = column[3]
                leave_type = column[4]

                _, created = Leave.objects.update_or_create(
                    employee=employee,
                    date=date_obj,
                    days=days,
                    type=leave_type
                )
            except Exception as e:
                log_error.append(str(e))

        if log_error:
            message_body = f"[WARNING] There are errors found in your csv file: {log_error}"
        else:
            message_body = "All data has uploaded successfully"

    elif csv_file_name == "offenses.csv":
        for column in csv.reader(io_string, delimiter=',', quotechar="|"):
            try:
                employee_tin_id = int(column[0])
                employee = Employee.objects.get(employee_tin_id=employee_tin_id)
                date_obj = (dateutil.parser.parse(column[2])).strftime("%Y-%m-%d")
                offense_name = column[3]

                _, created = Offense.objects.update_or_create(
                    employee=employee,
                    date=date_obj,
                    offense_name=offense_name
                )
            except Exception as e:
                log_error.append(str(e))

        if log_error:
            message_body = f"[WARNING] There are errors found in your csv file: {log_error}"
        else:
            message_body = "All data has uploaded successfully"
    elif csv_file_name == "earned_leaves.csv":
        year_today = datetime.datetime.now().year

        for column in csv.reader(io_string, delimiter=',', quotechar="|"):
            try:
                employee_tin_id = int(column[0])
                employee = Employee.objects.get(employee_tin_id=employee_tin_id)
                leave_type = column[2]
                month_earned_list = [
                    column[3],
                    column[4],
                    column[5],
                    column[6],
                    column[7],
                    column[8],
                    column[9],
                    column[10],
                    column[11],
                    column[12],
                    column[13],
                    column[14]
                ]

                for i in range(len(month_earned_list)):
                    month_num = i + 1
                    first_cut_off_date = 15
                    second_cut_off_date = calendar.monthrange(year_today, month_num)[1]

                    first_cut_off = datetime.date(year_today, month_num, first_cut_off_date)
                    second_cut_off = datetime.date(year_today, month_num, second_cut_off_date)
                    value = round(float(month_earned_list[i]) / 2, 3)

                    _, created = Earnedleave.objects.update_or_create(
                        employee=employee,
                        cut_off=first_cut_off,
                        value=value,
                        type=leave_type
                    )
                    _, created = Earnedleave.objects.update_or_create(
                        employee=employee,
                        cut_off=second_cut_off,
                        value=value,
                        type=leave_type
                    )
            except Exception as e:
                log_error.append(str(e))

        if log_error:
            message_body = f"[WARNING] There are errors found in your csv file: {log_error}"
        else:
            message_body = "All data has uploaded successfully"
    else:
        message_header = 'Error'
        message_body = "You CSV File is Invalid"

    return JsonResponse({"head": message_header, "body": message_body})

python/Web/hr_ptcc_project/employee_profile/templates/base.html
<!DOCTYPE html>
{# HTML5 declaration #}
<html>
    {# Make modifiable head elements #}
    <head>
        {% load static %}
        <title>{% block title %}PTCC HR{% endblock title %}</title>
        {% block head_favicon %}
            <link rel="icon" type="image/jpg"
                  href="{% static 'employee_profile/images/ptcc_icon.PNG' %}">
        {% endblock head_favicon %}
        {% block head_meta %}
            {% block head_meta_charset %}
                <meta http-equiv="Content-Type"
                      content="text/html; charset=utf-8" />
            {% endblock head_meta_charset %}
            {% block head_meta_contentlanguage %}
                <meta http-equiv="Content-Language" value="en-US" />
            {% endblock head_meta_contentlanguage %}
            {% block head_meta_viewport %}
                <meta name="viewport"
                      content="width=device-width, initial-scale=1.0">
            {% endblock head_meta_viewport %}
        {% endblock head_meta %}
        {% block head_css %}
            {% block head_css_site %}
                <link rel="stylesheet"
                      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
                      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
                      crossorigin="anonymous">
                <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
                    rel="stylesheet">
                <link rel="stylesheet" type="text/css" href="{% static 'employee_profile/css/style.css' %}">
            {% endblock head_css_site %}
            {% block head_css_section %}
            {% endblock head_css_section %}
            {% block head_css_page %}{% endblock head_css_page %}
        {% endblock head_css %}
        {% block head_js %}
            <script
                src="https://code.jquery.com/jquery-3.5.1.min.js"
                integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
                crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
                integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
                crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
                integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
                crossorigin="anonymous"></script>
        {% endblock head_js %}
        {% block custom_js %}{% endblock custom_js %}
    </head>
    <body>
        {# modal side bar #}
        <div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="uploadModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="uploadModalLabel">Uploade File</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div id="upload_label"></div>
                        <form id="upload_form" action="{% url 'upload_view' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <input id="file" type="file" name="file">
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal" id="cancel_button">Cancel</button>
                        <button type="submit" form="upload_form" class="btn btn-primary" id="upload_button">Upload</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="infoModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title info-modal-title" id="infoModalLabel"></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body info-modal-body"></div>
                    <div class="modal-footer">
                        <select id="year_selection" hidden="true"></select>
                        <button type="button" class="btn btn-secondary" id="info_button_close" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" id="generate_button" hidden="true">Generate</button>
                        <button type="button" class="btn btn-primary" id="delete_button" hidden="true">Delete</button>
                    </div>
                </div>
            </div>
        </div>
        {# The Document Body #}
        <div class="d-flex flex-column wrapper">
            {# Navigation Menu #}
            <!-- Navbar -->
            <div>
                <header>
                    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                        <div class="container-fluid">
                            <a class="navbar-brand" href="{% url 'employee_profile:index' %}">PTCC</a>
                            <button class="navbar-toggler" type="button"
                                    data-toggle="collapse" data-target="#navbarSupportedContent"
                                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                        </div>
                        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item">
                                    {% if user.is_authenticated %}
                                    <a class="nav-link" href="{% url 'logout' %}">SIGN OUT</a>
                                    {% endif %}
                                </li>
                            </ul>
                        </div>
                    </nav>
                </header>
            </div>
            <!-- Sidebar -->
            <div class="d-flex flex-row">
                <div>
                    <nav id="sidebar">
                        <div class="sidebar-header">
                            <a href="{% url 'employee_profile:index' %}"><h3>DOCUMENT GENERATOR</h3></a>
                        </div>
                        {% if user.is_authenticated %}
                        <ul class="list-unstyled components">
                        <li>
                            <a href="#uploadSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Upload Files</a>
                                <ul class="collapse list-unstyled" id="uploadSubmenu">
                                    <li>
                                        <a class="sidebar_button" id="upload_csv">Upload a CSV File</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="#generateSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Generate Files</a>
                                <ul class="collapse list-unstyled" id="generateSubmenu">
                                    <li>
                                        <a class="generate_sidebar_button" id="generate_lr">Generate Leave Registry</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                        {% endif %}
                    </nav>
                </div>
                <div>
                    {% block content %}
                        if you see this, something is wrong!
                    {% endblock content %}
                </div>
            </div>
            <!-- Footer -->
            <div>
                {# The Footer #}
                <footer class="page-footer font-small blue">
                    <!-- Copyright -->
                    <div class="footer-copyright text-center py-3">© 2020 Copyright:
                        <a href="http://www.ptcc.design/"> PTCC DESIGN</a>
                    </div>
                    <!-- Copyright -->
                </footer>
            </div>
        </div>
    </body>
    {# Set of blocks that can be used to display JavaScript files #}
    {% block footer_javascript %}
        {% block footer_javascript_section %}
            <script type="text/javascript">
                var url_generate = "{% url 'employee_profile:generate_leave_registry' %}";
                var url_upload = "{% url 'upload_view' %}";
                var url_download = "{% url 'employee_profile:download_file' %}";
                var checked_employee_list = [];
            </script>
            <script text="text/javascript" src="{% static 'employee_profile/js/base.js' %}"></script>
        {% endblock footer_javascript_section %}
        {% block footer_javascript_page %}{% endblock footer_javascript_page %}
    {% endblock footer_javascript %}
</html>