python/Web/hr_ptcc_project/employee_profile/urls.py
from django.urls import path
from . import views, apiViews

app_name = 'employee_profile'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.EmployeeDetailView.as_view(), name='employee_details'),
    path('save_changes', apiViews.save_changes, name='save_changes'),
    path('generate_leave_registry', apiViews.generate_leave_registry, name='generate_leave_registry'),
    path('download_file', apiViews.download_file, name='download_file'),
    path('add_employee', apiViews.add_employee, name='add_employee'),
    path('delete_employee', apiViews.delete_employee, name='delete_employee')
]

python/Web/hr_ptcc_project/hr_ptcc_project/urls.py
from django.contrib import admin
from django.urls import path, include
from employee_profile.views import upload_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employee_profile/', include('employee_profile.urls')),
    path('upload_files', upload_view, name='upload_view'),
    path('', include("django.contrib.auth.urls"))
]

python/Web/hr_ptcc_project/employee_profile/models.py
from django.db import models
from django.core import serializers
import datetime


class Employee(models.Model):
    REGULAR = 'R'
    REGULAR1 = 'R1'
    PROBATION = 'P'

    employee_status_choices = [
        (REGULAR, 'Regular Employee'),
        (REGULAR1, 'Regular1 Employee'),
        (PROBATION, 'Probationary Employee')
    ]

    employee_tin_id = models.IntegerField(default=0, unique=True)
    name = models.CharField(max_length=200)
    probation_date = models.DateField()
    hired_date = models.DateField()
    sl_start_date = models.DateField()
    regularization_date = models.DateField()
    employee_status = models.CharField(max_length=2,
                                       choices=employee_status_choices,
                                       default=PROBATION)
    prev_vl_bal = models.FloatField(default=0.0)
    prev_sl_bal = models.FloatField(default=0.0)

    def __str__(self):
        return self.name

    def get_total_leaves_taken(self):
        leaves_taken_obj_list = self.leave_set.all()
        sum_vl_taken = 0
        sum_sl_taken = 0

        for leaves_taken_obj in leaves_taken_obj_list:
            if leaves_taken_obj.type == "VL":
                sum_vl_taken += leaves_taken_obj.days
            elif leaves_taken_obj.type == "SL":
                sum_sl_taken += leaves_taken_obj.days

        return round(sum_vl_taken, 3), round(sum_sl_taken, 3)

    def get_earned_leaves(self):
        vl_list, sl_list = self.get_vl_sl_list()
        return zip(vl_list, sl_list)

    def get_leaves_taken(self):
        return serializers.serialize("json", self.leave_set.all())

    def get_offenses(self):
        return serializers.serialize("json", self.offense_set.all())

    def get_earned_vl_list(self):
        vl_list, sl_list = self.get_vl_sl_list()
        vl_list_serialized = serializers.serialize("json", vl_list)
        return vl_list_serialized

    def get_earned_sl_list(self):
        vl_list, sl_list = self.get_vl_sl_list()
        sl_list_serialized = serializers.serialize("json", sl_list)
        return sl_list_serialized

    def get_total_leaves(self):
        vl_list, sl_list = self.get_vl_sl_list()
        total_vl = self.prev_vl_bal
        total_sl = self.prev_sl_bal
        for vl in vl_list:
            total_vl += vl.value

        for sl in sl_list:
            total_sl += sl.value

        total_vl = round(total_vl, 3)
        total_sl = round(total_sl, 3)

        return total_vl, total_sl

    def get_vl_sl_list(self):
        emp_leaves = self.earnedleave_set.all()
        vl_list = []
        sl_list = []

        for leave in emp_leaves:
            if leave.type == 'VL':
                vl_list.append(leave)
            elif leave.type == 'SL':
                sl_list.append(leave)
        vl_list.sort(key=lambda x: x.cut_off)
        sl_list.sort(key=lambda x: x.cut_off)
        return vl_list, sl_list

    def get_timesheet_summary(self):
        emp_timesheet = self.timesheet_set.all()

        emp_timesheet_list = []
        for timesheet in emp_timesheet:
            if timesheet.time_in > datetime.time(hour=9, minute=0, second=0):
                late = 'YES'
            else:
                late = 'NO'

            if (timesheet.time_out - timesheet.time_in) < 8:
                ut = 'YES'
            else:
                ut = 'NO'

            emp_timesheet_list.append({'date': timesheet.date,
                                       'time_in': timesheet.time_in,
                                       'time_out': timesheet.time_out,
                                       'late': late,
                                       'ut': ut})
        return emp_timesheet_list


class Leave(models.Model):
    VL = 'VL'
    SL = 'SL'

    type_choices = [
        (VL, 'Vacation Leave'),
        (SL, 'Sick Leave')
    ]

    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    date = models.DateField()
    days = models.FloatField(default=0.0)
    type = models.CharField(max_length=2,
                            choices=type_choices,
                            default=VL)


class Offense(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    date = models.DateField()
    offense_name = models.CharField(max_length=20)


class Earnedleave(models.Model):
    VL = 'VL'
    SL = 'SL'

    type_choices = [
        (VL, 'Vacation Leave'),
        (SL, 'Sick Leave')
    ]

    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    cut_off = models.DateField()
    value = models.FloatField(default=0.0)
    type = models.CharField(max_length=2,
                            choices=type_choices,
                            default=VL)


class Timesheet(models.Model):

    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    date = models.DateField()
    time_in = models.TimeField()
    time_out = models.TimeField()
    project = models.CharField(max_length=200)

python/Web/hr_ptcc_project/employee_profile/forms.py
from django import forms


class EmployeeForm(forms.Form):
    sl_start_date = forms.DateField()
    regularization_date = forms.DateField()
    employee_status = forms.CharField(max_length=2)

python/Web/hr_ptcc_project/employee_profile/views.py
import csv
import io
from django.views import generic
from .models import Employee, Leave, Earnedleave, Offense, Timesheet
from django.contrib.auth.decorators import permission_required
from django.http import JsonResponse
from django.shortcuts import  redirect
import logging
import dateutil.parser
import datetime
import calendar
logger = logging.getLogger(__name__)


class IndexView(generic.ListView):
    template_name = 'employee_profile/index.html'
    context_object_name = 'latest_employee_list'

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return redirect('index')
        query = self.request.GET.get('search')
        if query:
            object_list = Employee.objects.filter(name__icontains=query)
        else:
            object_list = Employee.objects.order_by('name')
        return object_list

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('login')
        else:
            return super(IndexView, self).dispatch(request, *args, **kwargs)


class EmployeeDetailView(generic.DetailView):
    model = Employee
    template_name = 'employee_profile/employee_details.html'


@permission_required('admin.can_add_log_entry')
def upload_view(request):
    csv_file = request.FILES['file']
    csv_file_name = csv_file.name
    log_error = []
    message_header = 'Upload Done'

    if not csv_file_name.endswith('.csv'):
        return JsonResponse({"head": "Error", "body": "File must be CSV"})

    data_set = csv_file.read().decode('UTF-8')
    io_string = io.StringIO(data_set)
    next(io_string)

    if csv_file_name == "employee.csv":
        for column in csv.reader(io_string, delimiter=',', quotechar="|"):
            try:
                probation_date = (dateutil.parser.parse(column[2])).strftime("%Y-%m-%d")
                hired_date = (dateutil.parser.parse(column[3])).strftime("%Y-%m-%d")
                sl_start_date = (dateutil.parser.parse(column[4])).strftime("%Y-%m-%d")
                regularization_date = (dateutil.parser.parse(column[5])).strftime("%Y-%m-%d")

                _, created = Employee.objects.update_or_create(
                    employee_tin_id=column[0],
                    name=column[1],
                    probation_date=probation_date,
                    hired_date=hired_date,
                    sl_start_date=sl_start_date,
                    regularization_date=regularization_date,
                    employee_status=column[6],
                    prev_vl_bal=column[7],
                    prev_sl_bal=column[8],
                )
            except Exception as e:
                log_error.append(str(e))

        if log_error:
            message_body = f"[WARNING] There are errors found in your csv file: {log_error}"
        else:
            message_body = "All data has uploaded successfully"

    elif csv_file_name == "leaves.csv":
        for column in csv.reader(io_string, delimiter=',', quotechar="|"):
            try:
                employee_tin_id = int(column[0])
                employee = Employee.objects.get(employee_tin_id=employee_tin_id)
                date_obj = (dateutil.parser.parse(column[2])).strftime("%Y-%m-%d")
                days = column[3]
                leave_type = column[4]

                _, created = Leave.objects.update_or_create(
                    employee=employee,
                    date=date_obj,
                    days=days,
                    type=leave_type
                )
            except Exception as e:
                log_error.append(str(e))

        if log_error:
            message_body = f"[WARNING] There are errors found in your csv file: {log_error}"
        else:
            message_body = "All data has uploaded successfully"

    elif csv_file_name == "offenses.csv":
        for column in csv.reader(io_string, delimiter=',', quotechar="|"):
            try:
                employee_tin_id = int(column[0])
                employee = Employee.objects.get(employee_tin_id=employee_tin_id)
                date_obj = (dateutil.parser.parse(column[2])).strftime("%Y-%m-%d")
                offense_name = column[3]

                _, created = Offense.objects.update_or_create(
                    employee=employee,
                    date=date_obj,
                    offense_name=offense_name
                )
            except Exception as e:
                log_error.append(str(e))

        if log_error:
            message_body = f"[WARNING] There are errors found in your csv file: {log_error}"
        else:
            message_body = "All data has uploaded successfully"
    elif csv_file_name == "earned_leaves.csv":
        year_today = datetime.datetime.now().year

        for column in csv.reader(io_string, delimiter=',', quotechar="|"):
            try:
                employee_tin_id = int(column[0])
                employee = Employee.objects.get(employee_tin_id=employee_tin_id)
                leave_type = column[2]
                month_earned_list = [
                    column[3],
                    column[4],
                    column[5],
                    column[6],
                    column[7],
                    column[8],
                    column[9],
                    column[10],
                    column[11],
                    column[12],
                    column[13],
                    column[14]
                ]

                for i in range(len(month_earned_list)):
                    month_num = i + 1
                    first_cut_off_date = 15
                    second_cut_off_date = calendar.monthrange(year_today, month_num)[1]

                    first_cut_off = datetime.date(year_today, month_num, first_cut_off_date)
                    second_cut_off = datetime.date(year_today, month_num, second_cut_off_date)
                    value = round(float(month_earned_list[i]) / 2, 3)

                    _, created = Earnedleave.objects.update_or_create(
                        employee=employee,
                        cut_off=first_cut_off,
                        value=value,
                        type=leave_type
                    )
                    _, created = Earnedleave.objects.update_or_create(
                        employee=employee,
                        cut_off=second_cut_off,
                        value=value,
                        type=leave_type
                    )
            except Exception as e:
                log_error.append(str(e))

        if log_error:
            message_body = f"[WARNING] There are errors found in your csv file: {log_error}"
        else:
            message_body = "All data has uploaded successfully"
    else:
        message_header = 'Error'
        message_body = "You CSV File is Invalid"

    return JsonResponse({"head": message_header, "body": message_body})

python/Web/hr_ptcc_project/employee_profile/templates/employee_profile/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <body>
        <div class="center">
            <div class="d-flex justify-content-center">
                <div class="p-2"><h2>EMPLOYEE LIST</h2></div>
            </div>
            <div class="card_container">
                <form method="GET" id="searchForm">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Search by employee's name" aria-label="Employee's name" aria-describedby="basic-addon2" name="search" value='{{request.GET.search}}' id="searchEmployee">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" form="searchForm" type="submit">SEARCH</button>
                        </div>
                    </div>
                </form>
                
            </div>

            <div style="overflow:auto;height: 800px;">
                <div class="card_container">
                <div class="d-flex flex-column">
                    <div class="d-flex flex-row">
                        <div class="p-2">
                            <input type="checkbox" id="check_all_employee">
                            <label for="check_all_employee">Select All</label>
                        </div>
                        <div class="dropdown ml-auto p-2">
                            <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                                Actions
                                <span class="caret p-2"></span>
                            </button>
                            <ul class="dropdown-menu p-2">
                                <button class="dropdown-item" id="add-employee-button">Add Employee</button>
                                <button class="dropdown-item" id="delete-employee-button">Delete Employee</button>
                            </ul>
                        </div> 
                    </div>
                    <div>
                        {% if latest_employee_list %}
                        {% for employee in latest_employee_list %}
                            <form>
                                <div class="card">
                                    <div class="card-body">
                                        <div class="d-flex flex-row">
                                            <div class="p-1">
                                                <div>
                                                    <img src="{% static 'employee_profile/images/profile_icon.jpg' %}" alt="Trulli" width="100" height="100">
                                                </div>
                                            </div>
                                            <div class="p-1">
                                                <div class="employee_details">
                                                    <table>
                                                        <tr>
                                                            <td><h6 class="employee_name">Name:</h6></td>
                                                            <td><h6 class="employee_name"><strong>{{employee.name}}</strong></h6></td>
                                                        </tr>
                                                        <tr>
                                                            <td><h6 >Hired:</h6></td>
                                                            <td><h6><strong>{{employee.hired_date}}</strong></h6></td>
                                                        </tr>
                                                        <tr>
                                                            <td><h6>Status:</h6></td>
                                                            <td><h6><strong>{{employee.employee_status}}</strong></h6></td>
                                                        </tr>
                                                    </table>
                                                    <a href="{% url 'employee_profile:employee_details' employee.id %}" class="btn btn-primary stretched link">View Employee</a>
                                                </div>
                                            </div>
                                            <div class="ml-auto">
                                                <div class="form-check">
                                                    <input type="checkbox" class="form-check-input" 
                                                        data-id="{{employee.id}}" 
                                                        data-empname="{{employee.name}}" 
                                                        id="{{ employee.id }}">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        {% endfor %}
                        {% else %}
                            <div class="d-flex justify-content-center">
                                <div>
                                    <p>There are no Employees added yet.</p>
                                </div>
                            </div>
                        {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
    <div class="modal fade" id="addEmployeeModal" tabindex="-1" role="dialog" aria-labelledby="infoModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addEmployeeModalLabel">Add Employee</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="d-flex flex-column">
                        <form id="employee-input-form">
                            <div class="form-group">
                                <label for="emp-tin-input"><strong>Employee TIN Number</strong></label>
                                <input type="text" class="form-control add-input" data-type="format_float" name="emp_tin" id="emp-tin-input" aria-describedby="employeeTin" placeholder="Enter TIN Number">
                                <small class="error-text" hidden="true"></small>
                            </div>
                            <div class="form-group">
                                <label for="emp-name-input"><strong>Employee Name</strong></label>
                                <input type="text" class="form-control add-input" data-type="format_text" name="emp_name" id="emp-name-input" aria-describedby="employeeName" placeholder="Enter Full Name">
                                <small class="error-text" hidden="true"></small>
                            </div>
                            <div class="form-group">
                                <label for="hired-date-input"><strong>Hired Date</strong></label>
                                <input type="date" class="form-control add-input" data-type="format_date" name="emp_hired_date" id="hired-date-input" aria-describedby="hiredDate">
                                <small class="error-text" hidden="true"></small>
                            </div>
                            <div class="form-group">
                                <label for="probation-date-input"><strong>Probation Date</strong></label>
                                <input type="date" class="form-control add-input" data-type="format_date" name="emp_probation_date" id="probation-date-input" aria-describedby="probationDate">
                                <small class="error-text" hidden="true"></small>
                            </div>
                            <div class="form-group">
                                <label for="sl-start-date-input"><strong>SL Start Date</strong></label>
                                <input type="date" class="form-control add-input" data-type="format_date" name="emp_sl_start_date" id="sl-start-date-input" aria-describedby="sickStartDate">
                                <small class="error-text" hidden="true"></small>
                            </div>
                            <div class="form-group">
                                <label for="regularization-date-input"><strong>Regularization Date</strong></label>
                                <input type="date" class="form-control add-input" data-type="format_date" name="emp_reg_date" id="regularization-date-input" aria-describedby="regularizationDate">
                                <small class="error-text" hidden="true"></small>
                            </div>
                            <div class="form-group">
                                <label for="employee-status-select"><strong>Employee Status</strong></label>
                                <select class="form-control add-input" id="employee-status-select" data-type="format_select" name="emp_status">
                                    <option>R</option>
                                    <option>R1</option>
                                    <option>P</option>
                                </select>
                                <small class="error-text" hidden="true"></small>
                            </div>
                            <div class="form-group">
                                <label for="prev-vl-input"><strong>Previous VL Balance</strong></label>
                                <input type="text" class="form-control add-input" id="prev-vl-input" name="prev_vl_bal" aria-describedby="prevVl" placeholder="Enter Last Year's VL Balance" data-type="format_float">
                                <small class="error-text" hidden="true"></small>
                            </div>
                            <div class="form-group">
                                <label for="prev-sl-input"><strong>Previous SL Balance</strong></label>
                                <input type="text" class="form-control add-input" id="prev-sl-input" name="prev_sl_bal" aria-describedby="prevSl" placeholder="Enter Last Year's SL Balance" data-type="format_float">
                                <small class="error-text" hidden="true"></small>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" id="add-employee-button-neg" data-dismiss="modal">Cancel</button>
                    <button type="submit" form="employee-input-form" class="btn btn-primary" id="add-employee-button-pos">Add</button>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block custom_js %}
    <script type="text/javascript">
        var url_delete_employee = "{% url 'employee_profile:delete_employee' %}";
        var url_add_employee = "{% url 'employee_profile:add_employee' %}";
        var employeeIdList = [];
    </script>
    <script text="text/javascript" src="{% static 'employee_profile/js/index.js' %}"></script>
{% endblock %}

python/Web/hr_ptcc_project/employee_profile/templates/employee_profile/upload_files.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="uploadModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="uploadModalLabel">Uploade File</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="file" name="file">
                </form>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" id="cancel_button">Cancel</button>
            <button type="button" class="btn btn-primary" id="upload_button">Upload</button>
            </div>
        </div>
        </div>
    </div>
{% endblock %}